# The second stage sample {#stage2}

## Step 10: Within-community sampling

The sampling process that you use to select a sample from a community will depend on what the survey is investigating.

If you are investigating multiple indicators which apply to different groups of individuals then you may find it easier to use different sampling methods for different indicators. You can think of this as having different surveys for different indicators sampled from the same set of communities at the same time.

If you are evaluating a program treating SAM you can efficiently find SAM cases using an active and adaptive (snowball) case-finding method. If you are also evaluating TSFP and FBPM programs using house- to-house and door-to-door screening then you will not need to use active and adaptive case-finding as the screening process will also identify SAM cases. SAM is a rare condition. This means that estimates and maps of SAM prevalence and SAM treatment coverage may be based on only a small number of cases from a small number of sampling points. This problem can be avoided by using a “top-up” sample collected using an active and adaptive case-finding method in a small set of communities neighbouring the selected sampling point.

If you are evaluating (e.g.) TSFP and FBPM programs then the active and adaptive case-finding may only find the most severe cases. In this case, house-to-house and door-to-door screening will be the most appropriate way to find eligible persons (cases). If a sampling point is located in a village then the entire population can be screened. If a sampling point is located in a large village or town then the village or town can be divided into a set of segments and the entire population of only a sample of these segments are then screened (see **Appendix A**).

If you are evaluating a BCC program then you can apply your BCC questions to the carers of children and to the PLWs that you find in the sample.

\newpage

## Step 11: Collect and record the data

Datasets for need and coverage surveys of selective-entry feeding programs are usually simple and can be collected using simple tabular forms.

Here is an example of a form used to collect coverage data on TSFP and FPBM programs for children:

Here is an example of a form used to collect coverage data on TSFP and FPBM programs for PLWs:

The “BCC confirmed by message recall” column records whether the respondent can recall any messages that match with the program's BCC key messages.

The data collected using the tabular forms will allow you to estimate or classify need and coverage. They do not, however, allow you to know the reasons for coverage failure. To collect this data we apply a “barriers” questionnaire to uncovered cases (PLWs) or the carers of uncovered cases (children). Here is an example of a barriers questionnaire:

The barriers questionnaire is applied only to non-covered cases.

Remember to refer all non-covered cases to the appropriate program.

\newpage

## Step 12: Enter the collected data

Coverage survey data is simple enough to be entered (and analysed) using spreadsheet packages such as Microsoft Excel or OpenOffice Calc.

If you want to analyse your data using a spreadsheet then you can use column names that make sense to you. If you want to analyse your data using the **RAnalyticFlow** workflow (see **Step 13**) then the column names
**must** be **exactly**:

